# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use official Python slim image
FROM python:3.10-slim

# Set work directory
WORKDIR /app

# Install build dependencies
RUN apt-get update && apt-get install -y --no-install-recommends gcc

# Copy requirements and project files
COPY pyproject.toml ./
COPY LICENSE.md ./
COPY README.md ./
COPY uv.lock ./
COPY src/ ./src/
COPY tests/ ./tests/
COPY lint.sh ./

# Install the package without running scripts (ignore-scripts used if necessary)
RUN pip install --upgrade pip \
    && pip install .

# Expose port if necessary (MCP uses stdio, but add if needed)

# Set entrypoint command
ENTRYPOINT ["hubspot-mcp-server"]
